# Node.js Function App to Windows on Azure
# Build a Node.js function app and deploy it to Azure as a Windows function app.
# Add steps that build code, save build artifacts, deploy, and more:
name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
      uses: actions/checkout@master

      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: npm install --production
 
      - name: "Login via Azure CLI"
        uses: Azure/login@v1
        with
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: "Run Azure Fonctions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ismailalabou-trivia-api