name: Build and Deploy

on:
  push:
    branches: master

jobs:
  build_and_test:
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, test
        run: |
          npm install
          npm run build --if-present
          npm test
      - name: Archive code coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report-${{ matrix.os }}-node${{ matrix.node_version }}
          path: coverage/

      - name: label test files
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
